spring:
  profiles:
    active: local
  application:
    name: rong-ai-code-monther-backend
  session:
    store-type: redis
    timeout: 2592000
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://x.x.x.x:xxxx/rong_ai_code_mother
    username: xxx
    password: xxx
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rong.rongaicodemonther.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI 模型配置
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: xxxxxxxxxxxxxxxxxxxx
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: xxxxxxxxxxxxxx
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-reasoner
      max-tokens: 50000
      temperature: 1.0
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: xxx
      model-name: qwen-turbo
      max-tokens: 100
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name
# Pexels 图片搜索配置
pexels:
  api-key: <Your API Key>
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
