server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: ai-code-mother # 服务名称
#  profiles:
#    active: prod
  config:
    import: # Boot 3.x 官方推荐写法
      - nacos:rong-ai-code-mother-prod.yaml?group=prod
  nacos:
    config:
      server-addr: 127.0.0.1:8848

