server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: ai-code-mother # 服务名称
  profiles:
    active: dev # 当前使用dev环境
  config:
    import: # Boot 3.x 官方推荐写法
      - nacos:ai-code-mother-${spring.profiles.active}.yaml?group=dev
  nacos:
    config:
      server-addr: 127.0.0.1:8848

